path: /home/vfx/Documents/HoudiniProjects/TOPS_3DGRUT/images/0001
experiment_name: '0001'
resume: ''
out_dir: /home/vfx/Documents/HoudiniProjects/TOPS_3DGRUT/geo
n_iterations: 30000
with_gui: false
gui_update_from_device: true
val_frequency: 999999
num_workers: 24
use_wandb: false
wandb_project: 3dgrt
test_last: true
validate_first: false
log_frequency: 1
compute_extra_metrics: true
enable_frame_timings: false
enable_writer: true
writer:
  hit_stat_frequency: 999999
  max_num_hits: 128
  log_image_views: ${int_list:[ 0, 13, 27, 43, 78 ]}
export_ingp:
  enabled: true
  force_half: false
  path: ''
import_ingp:
  enabled: false
  path: ''
  init_global_step: 0
export_ply:
  enabled: true
  path: ''
import_ply:
  enabled: false
  path: ''
  init_global_step: 0
export_usdz:
  enabled: false
  path: ''
  apply_normalizing_transform: true
model:
  density_activation: sigmoid
  scale_activation: exp
  default_density: 0.1
  default_scale_factor: 1.0
  optimize_density: true
  optimize_features_albedo: true
  optimize_features_specular: true
  optimize_position: true
  optimize_rotation: true
  optimize_scale: true
  bvh_update_frequency: 1
  progressive_training:
    feature_type: sh
    init_n_features: 0
    max_n_features: 3
    increase_frequency: 1000
    increase_step: 1
  background:
    name: background-color
    color: black
  print_stats: true
checkpoint:
  iterations: ${int_list:[ 7000, 30000 ]}
optimizer:
  type: adam
  lr: 0.0
  eps: 1.0e-15
  params:
    positions:
      lr: 0.00016
    density:
      lr: 0.05
    features_albedo:
      lr: 0.0025
    features_specular:
      lr: ${div:${optimizer.params.features_albedo.lr},20}
    rotation:
      lr: 0.001
    scale:
      lr: 0.005
scheduler:
  positions:
    type: exp
    lr_init: ${optimizer.params.positions.lr}
    lr_final: 1.6e-06
    max_steps: 30000
  density:
    type: skip
loss:
  use_l1: true
  lambda_l1: 0.8
  use_l2: false
  lambda_l2: 1.0
  use_ssim: true
  lambda_ssim: 0.2
  use_opacity: false
  lambda_opacity: 0.0
  use_scale: false
  lambda_scale: 0.0
strategy:
  method: GSStrategy
  print_stats: true
  densify:
    params: positions
    frequency: 300
    start_iteration: 500
    end_iteration: 15000
    clone_grad_threshold: 0.0002
    split_grad_threshold: 0.0002
    relative_size_threshold: 0.01
    split:
      n_gaussians: 2
  prune:
    frequency: 100
    start_iteration: 500
    end_iteration: 15000
    density_threshold: 0.005
  reset_density:
    frequency: 3000
    start_iteration: 0
    end_iteration: ${strategy.densify.end_iteration}
    new_max_density: 0.01
  density_decay:
    gamma: 0.99
    start_iteration: -1
    end_iteration: -1
    frequency: 50
  prune_weight:
    frequency: 100
    start_iteration: -1
    end_iteration: -1
    weight_threshold: 0.5
  prune_scale:
    frequency: 100
    start_iteration: -1
    end_iteration: -1
    threshold: 1.0
dataset:
  type: colmap
  downsample_factor: 1
  test_split_interval: 8
initialization:
  method: colmap
  observation_scale_factor: 0.01
  use_observation_points: true
render:
  method: 3dgut
  pipeline_type: reference
  backward_pipeline_type: ${render.pipeline_type}Bwd
  particle_kernel_degree: 2
  particle_kernel_density_clamping: true
  particle_kernel_min_response: 0.0113
  particle_kernel_min_alpha: ${div:1.0,255.0}
  particle_kernel_max_alpha: 0.99
  particle_radiance_sph_degree: 3
  primitive_type: instances
  min_transmittance: 0.0001
  max_consecutive_bvh_update: 15
  enable_normals: false
  enable_hitcounts: true
  enable_kernel_timings: false
  splat:
    rect_bounding: true
    tight_opacity_bounding: true
    tile_based_culling: true
    n_rolling_shutter_iterations: 5
    ut_alpha: 1.0
    ut_beta: 2.0
    ut_kappa: 0.0
    ut_in_image_margin_factor: 0.1
    ut_require_all_sigma_points_valid: false
    k_buffer_size: 0
    global_z_order: true
